(executable
 (name run)
 (libraries
  ;; opam libraries
  base
  core_kernel
  async
  async_kernel
  async_unix
  ;; local librariesa
  mina_base
  mina_base.import
  pickles
  pickles.backend
  pickles_types
  snark_params
  snarky.backendless
  pickles_optional_custom_gates_circuits)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_snarky ppx_mina ppx_version ppx_jane ppx_compare h_list.ppx))
 (modules run test_circuit test_lookup))
